# fly.toml app configuration file generated for kanboard-winter-resonance-4338 on 2025-05-19T11:38:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kanboard-winter-resonance-4338"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  min_machines_running = 1
  processes = ["app"]

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[mounts]
  source = "kanboard_data"
  destination = "/var/www/app/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
